version: '2'
services:
    app:
        build: .
        ports:
            - "8080:8080"
        volumes:
            - .:/var/www/anagrams-search-service
        depends_on:
            - redis
    redis:
        image: "redis:5.0-alpine"